### ISSUE TITLE
Make Navbar Sticky for Better User Experience

### ISSUE THREAD

**Issue by Arnab7456** [psidh/chess#14]
Currently, the navbar scrolls out of view when users navigate the page. To enhance the user experience, make the navbar sticky so that it remains visible at the top of the screen. This will allow users to access navigation links and buttons without needing to scroll back up.

Benefits:

Improved navigation efficiency.
Easier access to key actions, enhancing usability.

**Comment by psidh** [comment]
solved by 9ca7e0e9f7f8fcf2d29e31f7efdf67b8d5a25171
